---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by v_pwlu.
--- DateTime: 2019/2/28 11:04
---

local resultArray = redis.call('zrangebyscore', KEYS[1], ARGV[1], ARGV[2], 'limit' , ARGV[3], ARGV[4])
if #resultArray > 0 then
    if redis.call('zrem', KEYS[1], resultArray[1]) > 0 then
        return resultArray[1]
    else
        return ''
    end
else
    return ''
end